/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import ravencell.TableActionCellEditor;
import ravencell.TableActionCellRender;
import ravencell.TableActionEvent;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 /*
 * @author cheta
 */

public class searchTrain extends javax.swing.JFrame {

    /**
     * Creates new form searchTrain
     */
    String dbURL = "jdbc:oracle:thin:@//Chetan:1521/XE";
    String dbUser = "Chetan";
    String dbPassword = "root";

    PreparedStatement pst = null;

    ResultSet rs = null;
    
    public searchTrain() {
        initComponents();
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void Book() {
                
            }
        };
        tblTraininfo.getColumnModel().getColumn(9).setCellRenderer(new TableActionCellRender());
        tblTraininfo.getColumnModel().getColumn(9).setCellEditor(new TableActionCellEditor(event));
        theader();
    }
    
    private void theader() {
        JTableHeader tHead = tblTraininfo.getTableHeader();
        tHead.setForeground(new Color (0,119,194));
        tHead.setBackground(Color.WHITE);
        
        TableColumn col1 = tblTraininfo.getColumnModel().getColumn(0);
        col1.setPreferredWidth(100);
        TableColumn col2 = tblTraininfo.getColumnModel().getColumn(1);
        col2.setPreferredWidth(100);
        TableColumn col3 = tblTraininfo.getColumnModel().getColumn(2);
        col3.setPreferredWidth(80);
        TableColumn col4 = tblTraininfo.getColumnModel().getColumn(3);
        col4.setPreferredWidth(100);
        TableColumn col5 = tblTraininfo.getColumnModel().getColumn(4);
        col5.setPreferredWidth(120);
        TableColumn col6 = tblTraininfo.getColumnModel().getColumn(5);
        col6.setPreferredWidth(100);
        TableColumn col7 = tblTraininfo.getColumnModel().getColumn(6);
        col7.setPreferredWidth(100);
        TableColumn col8 = tblTraininfo.getColumnModel().getColumn(7);
        col8.setPreferredWidth(100);
        TableColumn col9 = tblTraininfo.getColumnModel().getColumn(8);
        col9.setPreferredWidth(100);
        TableColumn col10 = tblTraininfo.getColumnModel().getColumn(9);
        col10.setPreferredWidth(100);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraininfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 600));

        jPanel1.setBackground(new java.awt.Color(0, 119, 194));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/magnifying-glass.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEARCH TRAIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 119, 194));
        jLabel2.setText("Source: ");

        txtSource.setBackground(new java.awt.Color(255, 255, 255));
        txtSource.setForeground(new java.awt.Color(0, 119, 194));
        txtSource.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 119, 194));
        jLabel4.setText("Destination: ");

        txtDestination.setBackground(new java.awt.Color(255, 255, 255));
        txtDestination.setForeground(new java.awt.Color(0, 119, 194));
        txtDestination.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        btnSearch.setBackground(new java.awt.Color(0, 119, 194));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblTraininfo.setBackground(new java.awt.Color(255, 255, 255));
        tblTraininfo.setForeground(new java.awt.Color(0, 0, 0));
        tblTraininfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Train Number", "Train Name", "Source_Station", "Destination_Station", "Departure_Time", "Arrival_Time", "Sleeper AVL", "2 AC AVL", "1 AC AVL", "Book Now"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTraininfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTraininfo.setFillsViewportHeight(true);
        tblTraininfo.setRowHeight(40);
        tblTraininfo.setSelectionBackground(new java.awt.Color(0, 119, 194));
        jScrollPane1.setViewportView(tblTraininfo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            ImageIcon icon = new ImageIcon("C:\\Users\\cheta\\OneDrive\\Documents\\NetBeansProjects\\Railway Reservation System\\src\\ravencell\\booking (1).png");
            //connect to database
            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPassword);
            //query to retrieve data
            String query = "SELECT TRAIN.Train_No, TRAIN.Train_Name, TRAIN.Source_Station, TRAIN.Destination_Station, "
                    + "ROUTE.Departure_Time, ROUTE.Arrival_Time, "
                    + "TRAINSL_STATUS.SL_AvailableSeats as Sleeper_Available, "
                    + "TRAINAC2_STATUS.AC2_AvailableSeats as AC2_Available, "
                    + "TRAINAC1_STATUS.AC1_AvailableSeats as AC1_Available "
                    + "FROM TRAIN "
                    + "INNER JOIN ROUTE ON TRAIN.Train_No = ROUTE.Train_No "
                    + "INNER JOIN TRAINSL_STATUS ON TRAIN.Train_No = TRAINSL_STATUS.Train_No "
                    + "INNER JOIN TRAINAC2_STATUS ON TRAIN.Train_No = TRAINAC2_STATUS.Train_No "
                    + "INNER JOIN TRAINAC1_STATUS ON TRAIN.Train_No = TRAINAC1_STATUS.Train_No "
                    + "WHERE TRAIN.Source_Station = ? AND TRAIN.Destination_Station = ?";

            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, txtSource.getText().trim());
            stmt.setString(2, txtDestination.getText().trim());

            //execute query and store results in ResultSet
            ResultSet rs = stmt.executeQuery();

            //create table model with column names
            String[] columnNames = {"Train Number", "Train Name", "Source Station", "Destination Station", "Departure Time", "Arrival Time", "Sleeper Available", "AC2 Available", "AC1 Available","Book Now"};
            DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
            
            //iterate through ResultSet and add data to table model
            while (rs.next()) {
                String trainNumber = rs.getString("Train_No");
                String trainName = rs.getString("Train_Name");
                String origin = rs.getString("Source_Station");
                String destination = rs.getString("Destination_Station");
                String departureTime = rs.getString("Departure_Time");
                String arrivalTime = rs.getString("Arrival_Time");
                int sleeperAvailable = rs.getInt("Sleeper_Available");
                int ac2Available = rs.getInt("AC2_Available");
                int ac1Available = rs.getInt("AC1_Available");
                Object[] rowData = {trainNumber, trainName, origin, destination, departureTime, arrivalTime, sleeperAvailable, ac2Available, ac1Available};
                tableModel.addRow(rowData);
            }
            
            TableActionCellRender renderer = new TableActionCellRender();
            tblTraininfo.getColumnModel().getColumn(9).setCellRenderer(renderer);


            //close ResultSet, PreparedStatement and Connection
            rs.close();
            stmt.close();
            conn.close();

            //set the table model to the JTable
            tblTraininfo.setModel(tableModel);
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchTrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTraininfo;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
