/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 /*
 * @author cheta
 */

public class searchTrain extends javax.swing.JFrame {

    /**
     * Creates new form searchTrain
     */
    String dbURL = "jdbc:oracle:thin:@//Chetan:1521/XE";
    String dbUser = "Chetan";
    String dbPassword = "root";

    PreparedStatement pst = null;

    ResultSet rs = null;
    
    private int userId;
    
    public searchTrain(int userId) {
        initComponents();
        theader();
        this.userId = userId;
    }
    
    private void theader() {
        JTableHeader tHead = tblTraininfo.getTableHeader();
        tHead.setForeground(new Color (0,119,194));
        tHead.setBackground(Color.WHITE);
        
        TableColumn col1 = tblTraininfo.getColumnModel().getColumn(0);
        col1.setPreferredWidth(100);
        TableColumn col2 = tblTraininfo.getColumnModel().getColumn(1);
        col2.setPreferredWidth(100);
        TableColumn col3 = tblTraininfo.getColumnModel().getColumn(2);
        col3.setPreferredWidth(80);
        TableColumn col4 = tblTraininfo.getColumnModel().getColumn(3);
        col4.setPreferredWidth(100);
        TableColumn col5 = tblTraininfo.getColumnModel().getColumn(4);
        col5.setPreferredWidth(120);
        TableColumn col6 = tblTraininfo.getColumnModel().getColumn(5);
        col6.setPreferredWidth(100);
        TableColumn col7 = tblTraininfo.getColumnModel().getColumn(6);
        col7.setPreferredWidth(100);
        TableColumn col8 = tblTraininfo.getColumnModel().getColumn(7);
        col8.setPreferredWidth(100);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraininfo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtFare = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        btnGetData = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblTrainNo = new javax.swing.JLabel();
        lblTrainName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDepTime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboClass = new javax.swing.JComboBox<>();
        txtUserID = new javax.swing.JTextField();
        spinNumOfPassengers = new javax.swing.JSpinner();
        btnBook = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblTotalFare = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 119, 194));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/magnifying-glass.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEARCH TRAIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 119, 194));
        jLabel2.setText("Source: ");

        txtSource.setBackground(new java.awt.Color(255, 255, 255));
        txtSource.setForeground(new java.awt.Color(0, 0, 0));
        txtSource.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 119, 194));
        jLabel4.setText("Destination: ");

        txtDestination.setBackground(new java.awt.Color(255, 255, 255));
        txtDestination.setForeground(new java.awt.Color(0, 0, 0));
        txtDestination.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        btnSearch.setBackground(new java.awt.Color(0, 119, 194));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblTraininfo.setBackground(new java.awt.Color(255, 255, 255));
        tblTraininfo.setForeground(new java.awt.Color(0, 0, 0));
        tblTraininfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train Number", "Train Name", "Source Station", "Destination Station", "Departure Time", "Arrival Time", "Fare", "Total Distance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTraininfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTraininfo.setFillsViewportHeight(true);
        tblTraininfo.setRowHeight(40);
        tblTraininfo.setSelectionBackground(new java.awt.Color(0, 119, 194));
        tblTraininfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTraininfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTraininfo);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 119, 194));
        jLabel5.setText("User_ID:");

        txtFare.setEditable(false);
        txtFare.setBackground(new java.awt.Color(255, 255, 255));
        txtFare.setForeground(new java.awt.Color(0, 0, 0));
        txtFare.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 119, 194));
        jLabel6.setText("Full Name:");

        lblFullName.setBackground(new java.awt.Color(255, 255, 255));
        lblFullName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(0, 0, 0));
        lblFullName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        btnGetData.setBackground(new java.awt.Color(0, 119, 194));
        btnGetData.setForeground(new java.awt.Color(255, 255, 255));
        btnGetData.setText("Get Data");
        btnGetData.setBorder(null);
        btnGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDataActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 119, 194));
        jLabel7.setText("Train No:");

        lblTrainNo.setBackground(new java.awt.Color(255, 255, 255));
        lblTrainNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTrainNo.setForeground(new java.awt.Color(0, 0, 0));
        lblTrainNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        lblTrainName.setBackground(new java.awt.Color(255, 255, 255));
        lblTrainName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTrainName.setForeground(new java.awt.Color(0, 0, 0));
        lblTrainName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 119, 194));
        jLabel8.setText("Train Name:");

        lblDepTime.setBackground(new java.awt.Color(255, 255, 255));
        lblDepTime.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDepTime.setForeground(new java.awt.Color(0, 0, 0));
        lblDepTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 119, 194));
        jLabel9.setText("Departure Time:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 119, 194));
        jLabel10.setText("Class:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 119, 194));
        jLabel11.setText("Fare:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 119, 194));
        jLabel12.setText("No. Of Passengers:");

        comboClass.setBackground(new java.awt.Color(255, 255, 255));
        comboClass.setForeground(new java.awt.Color(0, 0, 0));
        comboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sleeper", "AC3", "AC2", "AC1" }));

        txtUserID.setBackground(new java.awt.Color(255, 255, 255));
        txtUserID.setForeground(new java.awt.Color(0, 0, 0));
        txtUserID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));

        spinNumOfPassengers.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinNumOfPassengersStateChanged(evt);
            }
        });

        btnBook.setBackground(new java.awt.Color(0, 119, 194));
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Book");
        btnBook.setBorder(null);
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnGoBack.setBackground(new java.awt.Color(0, 119, 194));
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Go Back");
        btnGoBack.setBorder(null);
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 119, 194));
        jLabel13.setText("Total Fare:");

        lblTotalFare.setEditable(false);
        lblTotalFare.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalFare.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalFare.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 194)));
        lblTotalFare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTotalFareActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 119, 194));
        jLabel14.setText("Date Of Journey: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinNumOfPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTotalFare, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFullName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtFare, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrainNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(lblTrainName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(lblDepTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(comboClass, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserID, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addComponent(btnGetData, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnGetData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTrainNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTrainName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFare, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinNumOfPassengers, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblTotalFare, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            //connect to database
            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPassword);
            //query to retrieve data
            String source = txtSource.getText().toUpperCase().trim();
            String destination = txtDestination.getText().toUpperCase().trim();
            String query = "Select * from Train where source_station=? and destination_station = ?";

            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, source);
            stmt.setString(2, destination);

            //execute query and store results in ResultSet
            ResultSet rs = stmt.executeQuery();

            //create table model with column names

            DefaultTableModel tableModel = (DefaultTableModel) tblTraininfo.getModel();
            tableModel.setRowCount(0);
            //iterate through ResultSet and add data to table model
            while (rs.next()) {
                String trainNumber = rs.getString("Train_No");
                String trainName = rs.getString("Train_Name");
                String origin = rs.getString("Source_Station");
                String tdestination = rs.getString("Destination_Station");
                String departureTime = rs.getString("Departure_Time");
                String arrivalTime = rs.getString("Arrival_Time");
                String Fare = rs.getString("Fare");
                String tot_distance = rs.getString("Total_Distance");
                
                Object[] rowData = {trainNumber, trainName, origin, tdestination, departureTime, arrivalTime, Fare, tot_distance};
                tableModel.addRow(rowData);
            }

            //close ResultSet, PreparedStatement and Connection
            rs.close();
            stmt.close();
            conn.close();

            //set the table model to the JTable
            tblTraininfo.setModel(tableModel);
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDataActionPerformed
        // TODO add your handling code here:
        
        try {
            String id = txtUserID.getText();
            //connect to database
            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPassword);
            //query to retrieve data
            String query = "Select * from Tlogin where USER_ID = '" + id + "'";
            PreparedStatement stmt = conn.prepareStatement(query);
            
            //execute query and store results in ResultSet
            
            ResultSet rs = stmt.executeQuery();
            
            if(rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Record Not Found");
            } else {
                String fname = rs.getString(2);
                lblFullName.setText(fname.trim());
            }

            //close ResultSet, PreparedStatement and Connection
            rs.close();
            stmt.close();
            conn.close();
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnGetDataActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        String trainNo = lblTrainNo.getText();
        String classType = comboClass.getSelectedItem().toString();
        String numOfSeats = spinNumOfPassengers.getValue().toString();
        String userId = txtUserID.getText();
        String totFare = lblTotalFare.getText();
        
        DateFormat da = new SimpleDateFormat("dd-MM-yyyy");
        String date = da.format(txtDate.getDate());
        
        try {
            Connection con = DriverManager.getConnection(dbURL, dbUser, dbPassword);
            //SQL Statement to INSERT values into the table
            String Query = "INSERT INTO BOOKINGS(TRAIN_NO,CLASS_TYPE,NUMSEATS,USER_ID,DOJ,TOTAL_FARE) VALUES (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(Query);
            //set the values for the placeholders in the preparedstatement 
            pst.setString(1, trainNo);
            pst.setString(2, classType);
            pst.setString(3, numOfSeats);
            pst.setString(4, userId);
            pst.setString(5, date);
            pst.setString(6, totFare);
            pst.executeUpdate(); //Execute the SQL Statement to insert the values into the table 
            
            JOptionPane.showMessageDialog(null, "Ticket Booked");
            
            //retrieve data from BOOKINGS, TLOGIN, and TRAIN tables
            String bookingNoQuery = "SELECT PNR_NUMBER FROM BOOKINGS WHERE TRAIN_NO = ? AND USER_ID = ? AND NUMSEATS = ? AND TOTAL_FARE = ?";
            PreparedStatement bookingNoPst = con.prepareStatement(bookingNoQuery);
            bookingNoPst.setString(1, trainNo);
            bookingNoPst.setString(2, userId);
            bookingNoPst.setString(3, numOfSeats);
            bookingNoPst.setString(4, totFare);
            ResultSet bookingNoRs = bookingNoPst.executeQuery();
            bookingNoRs.next();
            String bookingNo = bookingNoRs.getString(1);
            
            String userQuery = "SELECT FULL_NAME, GENDER FROM TLOGIN WHERE USER_ID = ?";
            PreparedStatement userPst = con.prepareStatement(userQuery);
            userPst.setString(1, userId);
            ResultSet userRs = userPst.executeQuery();
            userRs.next();
            String fullName = userRs.getString(1);
            String gender = userRs.getString(2);
            
            String trainQuery = "SELECT TRAIN_NAME, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME FROM TRAIN WHERE TRAIN_NO = ?";
            PreparedStatement trainPst = con.prepareStatement(trainQuery);
            trainPst.setString(1, trainNo);
            ResultSet trainRs = trainPst.executeQuery();
            trainRs.next();
            String trainName = trainRs.getString(1);
            String sourceStation = trainRs.getString(2);
            String destinationStation = trainRs.getString(3);
            String departureTime = trainRs.getString(4);
            String arrivalTime = trainRs.getString(5);
            
            // Open the TicketFrame panel and set the retrieved data to the corresponding text fields
            TicketFrame tf = new TicketFrame();
            tf.txtBookedFrom.setText(sourceStation);
            tf.txtTo.setText(destinationStation);
            tf.txtDOJ.setText(date);
            tf.txtDepartureTime.setText(departureTime);
            tf.txtArrivalTime.setText(arrivalTime);
            tf.txtPnrNo.setText(bookingNo);
            tf.txtTrainNo.setText(trainNo);
            tf.txtTrainName.setText(trainName);
            tf.txtClass.setText(classType);
            tf.txtFullName.setText(fullName);
            tf.txtGender.setText(gender);
            tf.txtSeats.setText(numOfSeats);
            tf.txtTotalFare.setText(totFare);
            tf.setVisible(true);
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }         
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        UserDashboard ud = new UserDashboard(userId);
        this.hide();
        ud.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void tblTraininfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTraininfoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tblTraininfo.getModel();
        
        int selectIndex = tblTraininfo.getSelectedRow();
        
        lblTrainNo.setText(tableModel.getValueAt(selectIndex, 0).toString());
        lblTrainName.setText(tableModel.getValueAt(selectIndex, 1).toString());
        lblDepTime.setText(tableModel.getValueAt(selectIndex, 4).toString());
        txtFare.setText(tableModel.getValueAt(selectIndex, 6).toString());
    }//GEN-LAST:event_tblTraininfoMouseClicked

    private void lblTotalFareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTotalFareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalFareActionPerformed

    private void spinNumOfPassengersStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinNumOfPassengersStateChanged
        // TODO add your handling code here:
        int price = Integer.parseInt(txtFare.getText());
        int numOfSeats = Integer.parseInt(spinNumOfPassengers.getValue().toString());
        String classType = (String) comboClass.getSelectedItem();
        int totFare = price * numOfSeats;
        
        if(classType.equals("Sleeper")) {
            totFare -= 1000 * numOfSeats;
        } else if(classType.equals("AC3")) {
            totFare -= 800 * numOfSeats;
        } else if(classType.equals("AC2")) {
            totFare -= 500 * numOfSeats;
        }
        
        lblTotalFare.setText(String.valueOf(totFare));
    }//GEN-LAST:event_spinNumOfPassengersStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                searchTrain st = new searchTrain(0);
                st.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnGetData;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDepTime;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JTextField lblTotalFare;
    private javax.swing.JLabel lblTrainName;
    private javax.swing.JLabel lblTrainNo;
    private javax.swing.JSpinner spinNumOfPassengers;
    private javax.swing.JTable tblTraininfo;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFare;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
